--Conexion a DB tareas
\c tareas

-- Registros para la tabla "usuarios"
INSERT INTO usuarios (nombre, correo) VALUES
  ('John Doe', 'john.doe@example.com'),
  ('Jane Smith', 'jane.smith@example.com'),
  ('David Johnson', 'david.johnson@example.com'),
  ('Emily Williams', 'emily.williams@example.com'),
  ('Michael Brown', 'michael.brown@example.com'),
  ('Olivia Jones', 'olivia.jones@example.com'),
  ('William Davis', 'william.davis@example.com'),
  ('Sophia Miller', 'sophia.miller@example.com'),
  ('James Wilson', 'james.wilson@example.com'),
  ('Ava Taylor', 'ava.taylor@example.com'),
  ('Robert Anderson', 'robert.anderson@example.com'),
  ('Mia Thomas', 'mia.thomas@example.com'),
  ('Joseph Martinez', 'joseph.martinez@example.com'),
  ('Isabella Clark', 'isabella.clark@example.com'),
  ('David Johnson', 'david.johnson@example.com'),
  ('Sophia Anderson', 'sophia.anderson@example.com'),
  ('Alexander Lewis', 'alexander.lewis@example.com'),
  ('Emma Moore', 'emma.moore@example.com'),
  ('Jackson Jackson', 'jackson.jackson@example.com'),
  ('Ava Thompson', 'ava.thompson@example.com'),
  ('Samuel White', 'samuel.white@example.com'),
  ('Abigail Harris', 'abigail.harris@example.com'),
  ('Matthew Martin', 'matthew.martin@example.com'),
  ('Charlotte Hall', 'charlotte.hall@example.com'),
  ('Ethan Adams', 'ethan.adams@example.com'),
  ('Harper Garcia', 'harper.garcia@example.com'),
  ('Daniel Wright', 'daniel.wright@example.com'),
  ('Amelia Young', 'amelia.young@example.com'),
  ('Lucas Lopez', 'lucas.lopez@example.com'),
  ('Lily Scott', 'lily.scott@example.com');

  -- Registros para la tabla "tareas" relacionados con usuarios
INSERT INTO tareas (titulo, descripcion, completado, usuario_id) VALUES
  ('Tarea 1', 'Descripción de la tarea 1', true, 1),
  ('Tarea 2', 'Descripción de la tarea 2', false, 1),
  ('Tarea 3', 'Descripción de la tarea 3', false, 2),
  ('Tarea 4', 'Descripción de la tarea 4', true, 2),
  ('Tarea 5', 'Descripción de la tarea 5', false, 3),
  ('Tarea 6', 'Descripción de la tarea 6', true, 3),
  ('Tarea 7', 'Descripción de la tarea 7', true, 4),
  ('Tarea 8', 'Descripción de la tarea 8', false, 4),
  ('Tarea 9', 'Descripción de la tarea 9', false, 5),
  ('Tarea 10', 'Descripción de la tarea 10', true, 5),
  ('Tarea 11', 'Descripción de la tarea 11', false, 6),
  ('Tarea 12', 'Descripción de la tarea 12', false, 6),
  ('Tarea 13', 'Descripción de la tarea 13', false, 7),
  ('Tarea 14', 'Descripción de la tarea 14', true, 7),
  ('Tarea 15', 'Descripción de la tarea 15', false, 8),
  ('Tarea 16', 'Descripción de la tarea 16', true, 8),
  ('Tarea 17', 'Descripción de la tarea 17', true, 9),
  ('Tarea 18', 'Descripción de la tarea 18', false, 9),
  ('Tarea 19', 'Descripción de la tarea 19', false, 10),
  ('Tarea 20', 'Descripción de la tarea 20', true, 10),
  ('Tarea 21', 'Descripción de la tarea 21', false, 11),
  ('Tarea 22', 'Descripción de la tarea 22', true, 11),
  ('Tarea 23', 'Descripción de la tarea 23', true, 12),
  ('Tarea 24', 'Descripción de la tarea 24', false, 12),
  ('Tarea 25', 'Descripción de la tarea 25', false, 13),
  ('Tarea 26', 'Descripción de la tarea 26', true, 13),
  ('Tarea 27', 'Descripción de la tarea 27', false, 14),
  ('Tarea 28', 'Descripción de la tarea 28', true, 14),
  ('Tarea 29', 'Descripción de la tarea 29', true, 15),
  ('Tarea 30', 'Descripción de la tarea 30', false, 15);

  